# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 3.0"

gem "sinatra-contrib", "~> 3.0"

gem "mysql2", "~> 0.5.2"
