NAME=python

run:
	docker-compose build
	docker-compose up -d

stop:
	# docker stop ${NAME}_static_1 ${NAME}_app_1 ${NAME}_db_1
	# docker rm ${NAME}_static_1 ${NAME}_app_1 ${NAME}_db_1
	docker-compose down